### ISSUE TITLE
Add metrics used to policies

### ISSUE THREAD

**Issue by SeanMcOwen** [BlockScience/MSML#245]

**Comment by SeanMcOwen** [comment]
From @jshorish on another project:

> I like the idea of 'metrics_used', and can see where a metric e.g. "balanced budget inequality = FAIL" could work. Can this be strengthened to e.g. 'metrics_required', to emphasize that they must be taken into consideration?

I have a feeling that keeping it at metrics_used only is a better option, but here is why:

I believe we can use metrics_used to denote the metrics that are going to be part of a policy. But then within a policy and a policy option we can directly reference them. I.e. policy option 1 might be strict_option where metric_1 must equal True versus we have a policy option 2 where metric_1 is not required. I like the idea of keeping that flexibility but I also am not anchored to it, what do you think?

**Comment by SeanMcOwen** [comment]
@jshorish 

Right now there is a metrics class actually! The way you are referring to it would be a tiny bit different though. Mostly in that in the current case Metric A, Metric B, Metric C are all going to just be in class instance versus the way you are talking about it would be that there is MetricA(strict=False) and MetricA(strict=True) used multiple times since there could be infinite policy options that say they use metric A.

With using strict as an attribute of the metric, I think it is important to note that one pitfall is it wouldn't make sense necessarily on the non-boolean metric values. I.e. we might have inflation rate and that would be a number out instead of a True/False.

One option I have is to add in an optional parameter when creating the JSON version of policy options where it is says strict_checking_metric_indices = [0, 4, etc.]. This would denote which indices in the passed metrics are required to be True (and I would of course add in a check to make sure return type is bool for those metrics).

But I would also like to show you an example of how I think one can denote this kind of strict checking without adding this in first. Then after that, basically here is what I am thinking:

1. If the feature is still something you think would be beneficial to add in + you want it soon for client work -> I'll put it in as part of V0.2.4 when I do this issue
2. If it is something you still see benefit in adding but not with any urgency -> I'll add to either the V0.3 project or V0.4 project as a separate issue to support this strict checking mode
3. The way I have been going about it works for what you want to convey -> I'll implement this issue without strict checking

**Comment by SeanMcOwen** [comment]
Maybe what I can do is have something like special behaviors and the two options would be:

strict_checking -> a flag which means this metric will be used as a strict check in the computation
logging -> indicating this metrics outputs should get logged

But then again, logging can be something represented on mechanisms. I'm a bit torn on it

**Comment by jshorish** [comment]
@SeanMcOwen Nice that you've already got a metrics class! But I see your point--so perhaps we're overloading 'metric' here, when the case we're discussing is actually a _constraint_, in this case a restriction on the domain of a block. 

I know that space constraint handling is a future work item for the new version of cadCAD, while the existing version builds that into the PSUB policy call (or perhaps the state update, depending). For the Math Spec there appear to be two routes:
1. As we're discussing, the 'general' domain space is unrestricted and constraints appear in policy logic (via e.g. metrics);
2. The 'general' domain space is _piped_ through a 'constraints' block, with codomain 'admissible space'. The 'admissible space' is then the domain of the policy.

I find #2 appealing as it's compositional and allows for constraints to be updated via their own block, leaving the policy logic untouched. Then metrics are free to 'do what they're supposed to', i.e. provide an assessment of the system's operation, without worrying about assertions such as "is the point selected actually an admissible point"? Finally, this matches more closely to GDS (i.e. admissible sets are used as the point of departure), although this is a lesser concern. What do you think?

**Comment by SeanMcOwen** [comment]
For metrics used A/C will be:

- It connects to the spec object
- JSON validation is updated
- The markdown reporting incorporates it

**Comment by SeanMcOwen** [comment]
@jshorish I believe I actually have a future issues for the constraints where I want to make them dynamic like this!

Right now policies have constraints that can be anything because it is just a string, however, I want to make it so that constraints can be specified on both codomain + domain to act like assertions.

In that way they could be piping on either the input side or the output side and there can be many of them. What do you think about that? And perhaps the dynamic constraints can have the ability to take things in like: metrics used

**Comment by jshorish** [comment]
@SeanMcOwen That sounds perfect, esp. being able to ingest metrics_used. Zargham and I briefly discussed constraints and how to formulate within a block diagram, and he might also have additional insights---from my perspective the piping approach seems the most 'natural' for keeping domains/codomains uncluttered, while still allowing constraints to restrict the admissible set (at least for the MSML).
