### ISSUE TITLE
Feat: produce a json schema compatible spec

### ISSUE THREAD

**Issue by zcstarr** [BlockScience/MSML#87]
Summary:
The markdown specification is great to have to understand what all of the components, mean it would be great to see a json schema specification that can be validated and applied in code using json schema validation.  I think any of the drafts v7 and greater would really help. For reference: https://json-schema.org , 

Motivation: 
If you have a spec in json schema, you can do things like generate code for the math specification across languages. So if you need to machine parse the specification it'll make it easier to do so. Secondly, with a specification, you can then use editors like vscode to have auto complete for the specification, which will make it easier for people to write. The last thing would be validation becomes easier in different ecosystems, in typescript/javascript land there is ajv in python jsonschema 

I tip my hat towards seeing  something like  msml.schema.json and a that was easy hook to see msml schemas produce with the file pattern mycoolmodel.msml.json , then you can just use vscode to pick up the msml.schema.json and have it auto complete with validation when you're describing your model :) 

Something like this https://github.com/open-rpc/meta-schema/blob/master/schema.json

**Comment by zcstarr** [comment]
@SeanMcOwen curious what you think here, I'd be down to at least put a PR to make this happen

**Comment by SeanMcOwen** [comment]
@zcstarr I really like this idea! I am going to put it in to the roadmap for V0.3 just because there are a few critical things I want to do first, including a full update of the graphics engine. Thank you for bringing it up!

**Comment by SeanMcOwen** [comment]
Going to try using https://app.quicktype.io/ to convert from JSON to JSON schema
